# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    twig:
        mode: lazy
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media/cache'
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public'
    filter_sets:
        square:
            quality: 75
            filters:
               thumbnail:
                    size: [200, 200]
                    mode: outbound
        big:
            filters:
                relative_resize:
                    heighten: 400
                    allow_upscale: true
